name: SILENT_GHOST_VPS
on: [push, workflow_dispatch]

jobs:
  vps:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Install Tmate & Force Tunnel
        run: |
          sudo apt-get update && sudo apt-get install tmate -y
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait-for-connection
          echo "========================================================="
          echo "🚀 CONNECTION READY!"
          echo "---------------------------------------------------------"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "---------------------------------------------------------"
          echo "========================================================="
          # Keep it alive for 6 hours
          sleep 21600
